# Generated by Django 4.0.6 on 2022-11-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeapp', '0002_booktable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='person',
            field=models.CharField(choices=[('1', 'Person1'), ('2', 'Person2'), ('3', 'Person3'), ('4', 'Person4')], max_length=20),
        ),
    ]
